### ISSUE TITLE
error when python3 RLBench/tools/dataset_generator_hdf5.py --save_path Datasets --robot sawyer --tasks sorting_program5 --variations 1 --episodes_per_task 50 --onscreen_render=True

### ISSUE THREAD

**Issue by HMT7** [Boxjod/RLBench_ACT#2]
My environment is Ubuntu20.04，I have followed the tutorial strictly to install RLBench_ACT, but when running usage: python3 RLBench/tools/dataset_generator_hdf5.py --save_path Datasets --robot sawyer --tasks sorting_program5 --variations 1 --episodes_per_task 50 --onscreen_render=True , I get the following error:
FLAGS.onscreen_render=True, FLAGS.robot='sawyer'
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in "/home/seu-hmt/COPPELIASIM"
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Fatal Python error: Aborted

Current thread 0x00007f9b315a9700 (most recent call first):
  File "/home/seu-hmt/RLBench_ACT/PyRep/pyrep/backend/sim.py", line 46 in simExtLaunchUIThread
  File "/home/seu-hmt/RLBench_ACT/PyRep/pyrep/pyrep.py", line 55 in _run_ui_thread
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/threading.py", line 870 in run
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007f9b61d794c0 (most recent call first):
  File "/home/seu-hmt/RLBench_ACT/PyRep/pyrep/pyrep.py", line 101 in launch
  File "/home/seu-hmt/RLBench_ACT/RLBench/rlbench/environment.py", line 106 in launch
  File "RLBench/tools/dataset_generator_hdf5.py", line 131 in run
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/multiprocessing/process.py", line 108 in run
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/multiprocessing/process.py", line 315 in _bootstrap
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/multiprocessing/popen_fork.py", line 75 in _launch
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/multiprocessing/popen_fork.py", line 19 in __init__
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/multiprocessing/context.py", line 277 in _Popen
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/multiprocessing/context.py", line 224 in _Popen
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/multiprocessing/process.py", line 121 in start
  File "RLBench/tools/dataset_generator_hdf5.py", line 235 in <listcomp>
  File "RLBench/tools/dataset_generator_hdf5.py", line 235 in main
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/site-packages/absl/app.py", line 254 in _run_main
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/site-packages/absl/app.py", line 308 in run
  File "RLBench/tools/dataset_generator_hdf5.py", line 243 in <module>
Data collection done!
Traceback (most recent call last):
  File "RLBench/tools/dataset_generator_hdf5.py", line 243, in <module>
    app.run(main)
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "RLBench/tools/dataset_generator_hdf5.py", line 240, in main
    print(result_dict[i])
  File "<string>", line 2, in __getitem__
  File "/home/seu-hmt/anaconda3/envs/rlbench_act/lib/python3.8/multiprocessing/managers.py", line 850, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 0

**Comment by ihangbao** [comment]
I encountered the same problem，you can create a soft link from the actual path to the one expected by the script:

ln -s /home/seu-hmt/CoppeliaSim /home/seu-hmt/COPPELIASIM

**Comment by HMT7** [comment]
@ihangbao  Thank you very much for your response, it worked!
